// S105: bounded original-law coupled MC3 search. Local files only.
#include <bits/stdc++.h>
using namespace std; using I=unsigned __int128; using U=unsigned __int128;
string si(I v){if(!v)return "0";string s;while(v){s+=char('0'+v%10);v/=10;}reverse(s.begin(),s.end());return s;}
struct Model {array<int,3>L;vector<pair<int,int>>ex;};
struct Result{bool valid=false; I E=0;array<I,5>K{}; vector<U>pred;};
mt19937_64 rng; int rnd(int n){return rng()%n;} double unif(){return (rng()>>11)*0x1.0p-53;}
Result eval(const Model&m){Result o;auto L=m.L;int n=L[0]+L[1]+L[2]; if(n>78||L[0]<1||L[1]<1||L[2]<2)return o;int off[3]={0,L[0],L[0]+L[1]};int x=0,y=off[1],a=off[2],b=a+1;vector<U>p(n);vector<int>chain(n),idx(n);for(int c=0;c<3;c++)for(int j=0;j<L[c];j++){int z=off[c]+j;chain[z]=c;idx[z]=j;if(j)p[z]|=U(1)<<(z-1);} for(auto[u,v]:m.ex){if(u<0||v<0||u>=n||v>=n)return o;p[v]|=U(1)<<u;}for(int k=0;k<n;k++)for(int z=0;z<n;z++)if(p[z]>>k&1)p[z]|=p[k];for(int z=0;z<n;z++)if(p[z]>>z&1)return o;if(p[x]||p[y]||p[a]||p[b]!=(U(1)<<a))return o;for(int z=0;z<n;z++)if(z!=x&&z!=y&&z!=a&&z!=b&&!(p[z]>>x&1)&&!(p[z]>>y&1))return o;
vector<array<int,3>>req(n);for(int z=0;z<n;z++)for(int u=0;u<n;u++)if(p[z]>>u&1)req[z][chain[u]]=max(req[z][chain[u]],idx[u]+1);
int stride[3]={(L[1]+1)*(L[2]+1),L[2]+1,1};int sz=(L[0]+1)*stride[0];vector<I>F(sz),H(sz);vector<unsigned char>M(sz);F[sz-1]=1;for(int i=L[0];i>=0;i--)for(int j=L[1];j>=0;j--)for(int k=L[2];k>=0;k--){int st[3]={i,j,k},s=i*stride[0]+j*stride[1]+k;if(s==sz-1)continue;for(int c=0;c<3;c++)if(st[c]<L[c]){int z=off[c]+st[c];if(i>=req[z][0]&&j>=req[z][1]&&k>=req[z][2]){M[s]|=1<<c;F[s]+=F[s+stride[c]];}}}
H[0]=1; int first[5]={a,a,b,b,x},second[5]={x,y,x,y,y};for(int i=0;i<=L[0];i++)for(int j=0;j<=L[1];j++)for(int k=0;k<=L[2];k++){int st[3]={i,j,k},s=i*stride[0]+j*stride[1]+k;if(!H[s])continue;for(int c=0;c<3;c++)if(M[s]>>c&1){int z=off[c]+st[c],t=s+stride[c];H[t]+=H[s];for(int q=0;q<5;q++)if(z==first[q]&&st[chain[second[q]]]<=idx[second[q]])o.K[q]+=H[s]*F[t];}}
o.E=F[0];assert(H.back()==o.E);o.valid=true; o.pred=move(p);return o;}
array<I,5> oriented(const Result&o,int ori){if(!ori)return o.K;return {o.K[1],o.K[0],o.K[3],o.K[2],o.E-o.K[4]};}
array<double,5> margins(const Result&o,int ori,int side){auto K=oriented(o,ori);double E=(double)o.E;return {(double)K[0]/E-2./3,(double)K[1]/E-2./3,(double)K[4]/E-2./3,1./3-(double)K[2]/E,side? (double)K[3]/E-2./3:1./3-(double)K[3]/E};}
bool qualified(const Result&o,int ori){auto K=oriented(o,ori);return 3*K[0]>2*o.E&&3*K[1]>2*o.E&&3*K[4]>2*o.E&&3*K[2]<o.E;}
bool forbidden(const Result&o,int ori,int side){auto K=oriented(o,ori);return qualified(o,ori)&&(side?3*K[3]>2*o.E:3*K[3]<o.E);}
double score(const Result&o,int side,int flavor=0){double ans=-100;for(int ori=0;ori<2;ori++){auto v=margins(o,ori,side);double worst=*min_element(v.begin(),v.end()),neg=0;for(double z:v)neg+=min(z,0.); double s=worst+(flavor==0?.15:.65)*neg;ans=max(ans,s);}return ans;}
void save(string path,const Model&m,const Result&o,int ori,int side,string criterion){ofstream f(path);auto K=oriented(o,ori);auto v=margins(o,ori,side);f<<"{\n\"shape\":["<<m.L[0]<<","<<m.L[1]<<","<<m.L[2]<<"],\n\"extra_edges\":[";for(int i=0;i<(int)m.ex.size();i++){if(i)f<<",";f<<"["<<m.ex[i].first<<","<<m.ex[i].second<<"]";}f<<"],\n\"E\":\""<<si(o.E)<<"\",\n\"K\":[";for(int i=0;i<5;i++){if(i)f<<",";f<<"\""<<si(o.K[i])<<"\"";}f<<"],\n\"oriented_K\":[";for(int i=0;i<5;i++){if(i)f<<",";f<<"\""<<si(K[i])<<"\"";}f<<"],\n\"orientation\":"<<ori<<",\n\"target_side\":\""<<(side?"high":"low")<<"\",\n\"residual_qualified\":"<<(qualified(o,ori)?"true":"false")<<",\n\"criterion\":\""<<criterion<<"\",\n\"target_margins\":[";for(int i=0;i<5;i++){if(i)f<<",";f<<setprecision(18)<<v[i];}f<<"]\n}\n";}
Model generate(array<int,3>L){Model m{L,{}};int off[3]={0,L[0],L[0]+L[1]},used[3]={1,1,1};vector<int>order={0,off[1],off[2]};while((int)order.size()<L[0]+L[1]+L[2]){int c=rnd(3);if(used[c]<L[c])order.push_back(off[c]+used[c]++);}int a=off[2],b=a+1;double dens[]={0,.01,.03,.07,.15,.3};double density=dens[rnd(6)];if(L[2]>2)m.ex.push_back({rnd(2)?0:off[1],b+1});for(int i=0;i<(int)order.size();i++)for(int j=i+1;j<(int)order.size();j++){int u=order[i],v=order[j];int c1=u<off[1]?0:u<off[2]?1:2,c2=v<off[1]?0:v<off[2]?1:2;if(c1!=c2&&v!=b&&unif()<density)m.ex.push_back({u,v});}return m;}
Model family(int m,int r,int g=1,int h=2){Model p{{1,r+1,m+2},{}};int a=r+2;p.ex={{a,1+g},{0,1+h},{0,a+2}};return p;}
Model resize_chain(Model m,int c,int delta){int off[3]={0,m.L[0],m.L[0]+m.L[1]},oldend=off[c]+m.L[c],cut=oldend-1;vector<pair<int,int>>ex;for(auto[u,v]:m.ex){if(delta<0&&(u==cut||v==cut))continue;if(delta>0){if(u>=oldend)u++;if(v>=oldend)v++;}else{if(u>=oldend)u--;if(v>=oldend)v--;}ex.push_back({u,v});}m.L[c]+=delta;m.ex=move(ex);return m;}
Model mutate(Model m){if(unif()<.12){int c=rnd(3),d=unif()<.5?-1:1;return resize_chain(m,c,d);}int n=accumulate(m.L.begin(),m.L.end(),0),x=0,y=m.L[0],a=y+m.L[1],b=a+1;int changes=unif()<.07?2+rnd(4):1;for(int it=0;it<changes;it++){double u0=unif();if(m.ex.size()&&u0<.45)m.ex.erase(m.ex.begin()+rnd(m.ex.size()));else if(m.ex.size()&&u0<.66){int k=rnd(m.ex.size()),end=rnd(2),delta=rnd(2)?1:-1;int &z=end?m.ex[k].second:m.ex[k].first;z=max(0,min(n-1,z+delta));}else{int u=rnd(n),v=rnd(n);if(v==x||v==y||v==a||v==b||u==v)continue;int c1=u<y?0:u<a?1:2,c2=v<y?0:v<a?1:2;if(c1==c2)continue;if(find(m.ex.begin(),m.ex.end(),make_pair(u,v))==m.ex.end())m.ex.push_back({u,v});}}return m;}
struct Stats{long valid=0,dual=0,entry=0,residual=0,total_negative=0;double min_total=10;double closest[2]={-100,-100},closest_q[2]={-100,-100};Model bestq[2];bool hasq[2]={false,false};};
void record(const Model&m,const Result&o,Stats&st){if(!o.valid)return;st.valid++;bool dual=3*o.K[0]>2*o.E&&3*o.K[1]>2*o.E;st.dual+=dual;double total=(2.*(double)o.K[2]+2.*(double)o.K[3]-(double)o.K[0]-(double)o.K[1])/(double)o.E;if(total<st.min_total){st.min_total=total;save("minimum_total_candidate.json",m,o,0,0,"min 2(q+r)-(Ax+Ay), no probability premises");}if(2*(o.K[2]+o.K[3])<o.K[0]+o.K[1])st.total_negative++;
if(dual&&3*o.K[2]<o.E&&3*o.K[3]<o.E){save("DUAL_LOW_COUNTEREXAMPLE.json",m,o,0,0,"dual a majority with both b marginals below 1/3");cerr<<"DUAL-LOW counterexample\n";}
for(int ori=0;ori<2;ori++){auto K=oriented(o,ori);if(dual&&3*K[4]>2*o.E)st.entry++;bool qu=qualified(o,ori);st.residual+=qu;for(int side=0;side<2;side++){auto v=margins(o,ori,side);double worst=*min_element(v.begin(),v.end());string suffix=side?"high":"low";if(worst>st.closest[side]){st.closest[side]=worst;save("nearest_"+suffix+".json",m,o,ori,side,"maximum minimum of all five signed target margins");}if(qu&&v[4]>st.closest_q[side]){st.closest_q[side]=v[4];st.bestq[side]=m;st.hasq[side]=true;save("nearest_residual_"+suffix+".json",m,o,ori,side,"maximum final signed target margin subject to first four strict premises");}if(forbidden(o,ori,side)){save("MC3_COUNTEREXAMPLE_"+suffix+".json",m,o,ori,side,"all five strict target inequalities");throw runtime_error("MC3 counterexample: independent verification required");}}}}
int main(int argc,char**argv){uint64_t seed=argc>1?stoull(argv[1]):105202610;int restarts=argc>2?stoi(argv[2]):120,steps=argc>3?stoi(argv[3]):700,fbudget=argc>4?stoi(argv[4]):30000;rng.seed(seed);Stats st;auto start=chrono::steady_clock::now();
// Structured bounded first pass includes the actual S104 L counterexample.
for(int r=2;r<=18;r++)for(int m=1;m+r+4<=78;m++){Model p=family(m,r);record(p,eval(p),st);}
for(int rep=0;rep<fbudget;rep++){int r=2+rnd(30),m=1+rnd(78-r-4),g=1+rnd(r-1),h=g+1+rnd(r-g);Model p=family(m,r,g,h);if(rep%3==0){int a=r+2;int u=(rnd(2)?a+1:1)+rnd(2);int v=1+rnd(r+1);if(v>1)p.ex.push_back({u,v});}if(rep%3==1){int a=r+2;p.ex.push_back({1+rnd(r+1),a+2+rnd(m)});}auto o=eval(p);record(p,o,st);}
cout<<"structured done: valid="<<st.valid<<" residual="<<st.residual<<" nearest_residual="<<st.closest_q[0]<<","<<st.closest_q[1]<<"\n"<<flush;
for(int side=0;side<2;side++)for(int rr=0;rr<restarts;rr++){Model m;if(rr%4==0&&st.hasq[side])m=st.bestq[side];else if(rr%4==1)m=family(54,15);else if(rr%4==2)m=Model{{2,7,11},{{2,11},{10,3},{10,4},{9,1}}};else {array<int,3>L={1+rnd(22),1+rnd(22),2+rnd(25)};m=generate(L);}Result o=eval(m);if(!o.valid){rr--;continue;}record(m,o,st);int flavor=rr%2;bool preserve=rr%4==0;for(int s=0;s<steps;s++){Model c=mutate(m);Result q=eval(c);if(!q.valid)continue;record(c,q,st);bool cq=qualified(q,0)||qualified(q,1),oq=qualified(o,0)||qualified(o,1);double so=score(o,side,flavor),sq=score(q,side,flavor);if(preserve&&oq&&!cq)continue;if(preserve&&oq&&cq){int oi=qualified(o,0)?0:1,qi=qualified(q,0)?0:1;so=margins(o,oi,side)[4];sq=margins(q,qi,side)[4];}double T=.007*(1.-(double)s/steps)+.00002;if(sq>=so||unif()<exp(max(-700.,(sq-so)/T))){m=move(c);o=move(q);}}
if(rr%10==0)cout<<"side="<<side<<" restart="<<rr<<" valid="<<st.valid<<" dual="<<st.dual<<" residual="<<st.residual<<" best="<<st.closest[side]<<" residual_target="<<st.closest_q[side]<<" seconds="<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n"<<flush;}
ofstream f("summary.json");f<<"{\"seed\":"<<seed<<",\"restarts_per_side\":"<<restarts<<",\"steps_per_restart\":"<<steps<<",\"random_structured_proposals\":"<<fbudget<<",\"family_grid\":\"2<=r<=18, 1<=m, m+r+4<=78, g=1,h=2\",\"valid_evaluations\":"<<st.valid<<",\"dual_majority_evaluations\":"<<st.dual<<",\"oriented_entry_majority_evaluations\":"<<st.entry<<",\"residual_qualified_evaluations\":"<<st.residual<<",\"total_candidate_negative_evaluations\":"<<st.total_negative<<",\"minimum_total_candidate\":"<<setprecision(18)<<st.min_total<<",\"closest_all_margin\":["<<st.closest[0]<<","<<st.closest[1]<<"],\"closest_residual_final_margin\":["<<st.closest_q[0]<<","<<st.closest_q[1]<<"],\"counterexample_found\":false,\"elapsed_seconds\":"<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"}\n";
}
