#include <bits/stdc++.h>
using namespace std; using I=unsigned __int128; using U=uint64_t;
string si(I v){if(!v)return "0";string s;while(v){s+=char('0'+v%10);v/=10;}reverse(s.begin(),s.end());return s;}
struct Model {array<int,3>L;vector<pair<int,int>>ex;};
struct Result{bool valid=false; I E=0;array<I,5>K{}; double score=-1,delta=1;int orient=0; bool qualified=false; vector<U>pred;};
mt19937_64 rng; int rnd(int n){return rng()%n;} double unif(){return (rng()>>11)*0x1.0p-53;}
Result eval(const Model&m){Result o;auto L=m.L;int n=L[0]+L[1]+L[2]; if(n>60)return o;int off[3]={0,L[0],L[0]+L[1]};int x=0,y=off[1],a=off[2],b=a+1;vector<U>p(n);vector<int>chain(n),idx(n);for(int c=0;c<3;c++)for(int j=0;j<L[c];j++){int z=off[c]+j;chain[z]=c;idx[z]=j;if(j)p[z]|=1ULL<<(z-1);} for(auto[u,v]:m.ex)p[v]|=1ULL<<u;for(int k=0;k<n;k++)for(int z=0;z<n;z++)if(p[z]>>k&1)p[z]|=p[k];for(int z=0;z<n;z++)if(p[z]>>z&1)return o;if(p[x]||p[y]||p[a]||p[b]!=(1ULL<<a))return o;for(int z=0;z<n;z++)if(z!=x&&z!=y&&z!=a&&z!=b&&!(p[z]>>x&1)&&!(p[z]>>y&1))return o;
vector<array<int,3>>req(n);for(int z=0;z<n;z++)for(int u=0;u<n;u++)if(p[z]>>u&1)req[z][chain[u]]=max(req[z][chain[u]],idx[u]+1);
int stride[3]={(L[1]+1)*(L[2]+1),L[2]+1,1};int sz=(L[0]+1)*stride[0];vector<I>F(sz),H(sz);vector<unsigned char>M(sz);F[sz-1]=1;for(int i=L[0];i>=0;i--)for(int j=L[1];j>=0;j--)for(int k=L[2];k>=0;k--){int st[3]={i,j,k},s=i*stride[0]+j*stride[1]+k;if(s==sz-1)continue;for(int c=0;c<3;c++)if(st[c]<L[c]){int z=off[c]+st[c];if(i>=req[z][0]&&j>=req[z][1]&&k>=req[z][2]){M[s]|=1<<c;F[s]+=F[s+stride[c]];}}}
H[0]=1; int first[5]={a,a,b,b,x},second[5]={x,y,x,y,y};for(int i=0;i<=L[0];i++)for(int j=0;j<=L[1];j++)for(int k=0;k<=L[2];k++){int st[3]={i,j,k},s=i*stride[0]+j*stride[1]+k;if(!H[s])continue;for(int c=0;c<3;c++)if(M[s]>>c&1){int z=off[c]+st[c],t=s+stride[c];H[t]+=H[s];for(int q=0;q<5;q++)if(z==first[q]&&st[chain[second[q]]]<=idx[second[q]])o.K[q]+=H[s]*F[t];}}
o.E=F[0];assert(H.back()==o.E);o.valid=true; o.pred=p;double e=(double)o.E;
for(int ori=0;ori<2;ori++){I ax=o.K[ori],ay=o.K[1-ori],bx=o.K[2+ori],pp=ori?o.E-o.K[4]:o.K[4];double mm=min({(double)ax/e-2./3,(double)ay/e-2./3,(double)pp/e-2./3});double d=(2*(double)bx-(double)ax)/e;double score=min(mm,-d);bool qualified=3*ax>2*o.E&&3*ay>2*o.E&&3*pp>2*o.E;if(score>o.score){o.score=score;o.orient=ori;}if(qualified){o.qualified=true;o.orient=ori;o.delta=d;}}
return o;}
void save(string path,const Model&m,const Result&o){ofstream f(path);f<<"{\n\"shape\":["<<m.L[0]<<","<<m.L[1]<<","<<m.L[2]<<"],\n\"extra_edges\":[";for(int i=0;i<(int)m.ex.size();i++){if(i)f<<",";f<<"["<<m.ex[i].first<<","<<m.ex[i].second<<"]";}f<<"],\n\"E\":\""<<si(o.E)<<"\",\n\"K\":[";for(int i=0;i<5;i++){if(i)f<<",";f<<"\""<<si(o.K[i])<<"\"";}f<<"],\n\"orientation\":"<<o.orient<<",\n\"qualified\":"<<(o.qualified?"true":"false")<<",\n\"half_delta\":"<<setprecision(18)<<o.delta<<",\n\"objective\":"<<o.score<<"\n}\n";}
Model generate(array<int,3>L){Model m{L,{}};int off[3]={0,L[0],L[0]+L[1]},used[3]={1,1,1};vector<int>order={0,off[1],off[2]};while((int)order.size()<L[0]+L[1]+L[2]){int c=rnd(3);if(used[c]<L[c])order.push_back(off[c]+used[c]++);}int a=off[2],b=a+1;double dens[]={0,.01,.03,.07,.15,.3};double density=dens[rnd(6)];if(L[2]>2)m.ex.push_back({rnd(2)?0:off[1],b+1});for(int i=0;i<(int)order.size();i++)for(int j=i+1;j<(int)order.size();j++){int u=order[i],v=order[j];int c1=u<off[1]?0:u<off[2]?1:2,c2=v<off[1]?0:v<off[2]?1:2;if(c1!=c2&&v!=b&&unif()<density)m.ex.push_back({u,v});}return m;}
Model mutate(Model m){int n=accumulate(m.L.begin(),m.L.end(),0),x=0,y=m.L[0],a=y+m.L[1],b=a+1; int changes=unif()<.08?2+rnd(4):1;for(int it=0;it<changes;it++){if(m.ex.size()&&unif()<.52){m.ex.erase(m.ex.begin()+rnd(m.ex.size()));}else{int u=rnd(n),v=rnd(n);if(v==x||v==y||v==a||v==b||u==v)continue;int c1=u<y?0:u<a?1:2,c2=v<y?0:v<a?1:2;if(c1==c2)continue;if(find(m.ex.begin(),m.ex.end(),make_pair(u,v))==m.ex.end())m.ex.push_back({u,v});}}return m;}
int main(int argc,char**argv){uint64_t seed=argc>1?stoull(argv[1]):104202610;int restarts=argc>2?stoi(argv[2]):300,steps=argc>3?stoi(argv[3]):1000;rng.seed(seed);long valid=0,qual=0;double best=-1,mindelta=1;auto start=chrono::steady_clock::now();Model eq{{2,7,11},{{2,11},{10,3},{10,4},{9,1}}};for(int r=0;r<restarts;r++){Model m;if(r%5==0)m=eq;else{array<int,3>L={1+rnd(20),1+rnd(20),2+rnd(20)};m=generate(L);}Result o=eval(m);if(!o.valid){r--;continue;}for(int s=0;s<steps;s++){Model c=mutate(m);Result q=eval(c);if(!q.valid)continue;valid++;if(q.qualified){qual++;if(q.delta<mindelta){mindelta=q.delta;save("best_qualified.json",c,q);}int ori=q.orient;if(2*q.K[2+ori]<q.K[ori]){save("COUNTEREXAMPLE.json",c,q);cout<<"COUNTEREXAMPLE seed="<<seed<<" r="<<r<<" step="<<s<<" valid="<<valid<<" qualified="<<qual<<"\n";ofstream f("summary.json");f<<"{\"seed\":"<<seed<<",\"planned_restarts\":"<<restarts<<",\"steps_per_restart\":"<<steps<<",\"stopped_restart_zero_based\":"<<r<<",\"stopped_step_zero_based\":"<<s<<",\"valid_evaluations\":"<<valid<<",\"qualified_evaluations\":"<<qual<<",\"counterexample_found\":true}";return 2;}}if(q.score>best){best=q.score;save("best_objective.json",c,q);}double T=.006*(1-(double)s/steps)+.00005;if(q.score>=o.score||unif()<exp(max(-700.,(q.score-o.score)/T))){m=move(c);o=move(q);}}
if(r%10==0){cout<<"restart="<<r<<" valid="<<valid<<" qualified="<<qual<<" best="<<setprecision(15)<<best<<" min_delta="<<mindelta<<" seconds="<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n"<<flush;}}
ofstream f("summary.json");f<<"{\"seed\":"<<seed<<",\"restarts\":"<<restarts<<",\"steps\":"<<steps<<",\"valid_evaluations\":"<<valid<<",\"qualified_evaluations\":"<<qual<<",\"best_objective\":"<<setprecision(18)<<best<<",\"minimum_qualified_delta\":"<<mindelta<<",\"counterexample_found\":false}";}
